# Generated by Django 4.1.3 on 2022-12-05 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='quiz_category',
            name='an_svg',
            field=models.FileField(null=True, upload_to='svg/', validators=[django.core.validators.FileExtensionValidator(['svg', 'pdf', 'doc'])]),
        ),
    ]
