# Generated by Django 4.1.3 on 2022-12-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_subjectmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaterial',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
