# Generated by Django 4.1.3 on 2022-12-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_subjectmaterial_url'),
        ('quiz', '0006_alter_comments_comment_text'),
    ]

    operations = [
    ]
