# Generated by Django 4.1.3 on 2022-12-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_category_cat_remove_quiz_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
