# Generated by Django 4.1.3 on 2022-12-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_comments_author_comments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('url', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('url', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
