# Generated by Django 4.1.3 on 2022-12-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_comments_author_comments_author_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_category',
            name='quiz_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz_category',
            name='quiz_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz_category',
            name='quiz_3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
