# Generated by Django 4.1.3 on 2022-12-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_category_quiz_1_quiz_category_quiz_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
