# Generated by Django 4.1.3 on 2022-12-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_footerinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinformation',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
