# Generated by Django 4.1.3 on 2022-12-14 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_footerinformation_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinformation',
            name='icon',
            field=models.FileField(null=True, upload_to='svg/', validators=[django.core.validators.FileExtensionValidator(['svg', 'pdf', 'doc'])]),
        ),
    ]
