# Generated by Django 4.1.3 on 2022-12-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_beforecategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeforeCategories',
            new_name='IntroductionCategories',
        ),
    ]
