# Generated by Django 4.1.3 on 2022-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_aboutusimages_aboutusreason_aboutustitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsWHY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
