# Generated by Django 4.1.3 on 2022-11-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizland', '0005_quiz_items_alter_answers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
