# Generated by Django 4.1.3 on 2022-11-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizland', '0009_alter_quizlinks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_items',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz_items',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='quiz_items',
            name='topic',
        ),
    ]
