# Generated by Django 4.1.3 on 2022-12-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizland', '0010_remove_quiz_items_image_remove_quiz_items_sub_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_items',
            old_name='subject',
            new_name='title',
        ),
    ]
