# Generated by Django 4.1.3 on 2022-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizland', '0011_rename_subject_quiz_items_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(default='some_value', max_length=25)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Quizlinks',
        ),
    ]
